// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: blackhole.proto

package blackhole

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Bytes) Reset() {
	*x = Bytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blackhole_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bytes) ProtoMessage() {}

func (x *Bytes) ProtoReflect() protoreflect.Message {
	mi := &file_blackhole_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bytes.ProtoReflect.Descriptor instead.
func (*Bytes) Descriptor() ([]byte, []int) {
	return file_blackhole_proto_rawDescGZIP(), []int{0}
}

func (x *Bytes) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ByteCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ByteCount) Reset() {
	*x = ByteCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blackhole_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByteCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteCount) ProtoMessage() {}

func (x *ByteCount) ProtoReflect() protoreflect.Message {
	mi := &file_blackhole_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteCount.ProtoReflect.Descriptor instead.
func (*ByteCount) Descriptor() ([]byte, []int) {
	return file_blackhole_proto_rawDescGZIP(), []int{1}
}

func (x *ByteCount) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length uint32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Count  uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *StreamSize) Reset() {
	*x = StreamSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blackhole_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSize) ProtoMessage() {}

func (x *StreamSize) ProtoReflect() protoreflect.Message {
	mi := &file_blackhole_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSize.ProtoReflect.Descriptor instead.
func (*StreamSize) Descriptor() ([]byte, []int) {
	return file_blackhole_proto_rawDescGZIP(), []int{2}
}

func (x *StreamSize) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *StreamSize) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_blackhole_proto protoreflect.FileDescriptor

var file_blackhole_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x22, 0x21, 0x0a, 0x05,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x21, 0x0a, 0x09, 0x42, 0x79, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xba,
	0x01, 0x0a, 0x09, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x41, 0x6c, 0x6c, 0x12, 0x10, 0x2e, 0x62, 0x6c, 0x61,
	0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x1a, 0x14, 0x2e, 0x62,
	0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x00, 0x28, 0x01, 0x12, 0x39, 0x0a, 0x0a, 0x45, 0x6d, 0x69, 0x74, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x15, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x1a, 0x10, 0x2e, 0x62, 0x6c,
	0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x38, 0x0a, 0x09, 0x45, 0x6d, 0x69, 0x74, 0x5a, 0x65, 0x72, 0x6f, 0x73, 0x12, 0x15,
	0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x53, 0x69, 0x7a, 0x65, 0x1a, 0x10, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c,
	0x65, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x42, 0x5f, 0x0a, 0x29, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6a, 0x7a, 0x68, 0x61, 0x6e, 0x67,
	0x30, 0x34, 0x36, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x30, 0x34, 0x36,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x2d,
	0x67, 0x6f, 0x2f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x6f, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blackhole_proto_rawDescOnce sync.Once
	file_blackhole_proto_rawDescData = file_blackhole_proto_rawDesc
)

func file_blackhole_proto_rawDescGZIP() []byte {
	file_blackhole_proto_rawDescOnce.Do(func() {
		file_blackhole_proto_rawDescData = protoimpl.X.CompressGZIP(file_blackhole_proto_rawDescData)
	})
	return file_blackhole_proto_rawDescData
}

var file_blackhole_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blackhole_proto_goTypes = []interface{}{
	(*Bytes)(nil),      // 0: blackhole.Bytes
	(*ByteCount)(nil),  // 1: blackhole.ByteCount
	(*StreamSize)(nil), // 2: blackhole.StreamSize
}
var file_blackhole_proto_depIdxs = []int32{
	0, // 0: blackhole.BlackHole.ConsumeAll:input_type -> blackhole.Bytes
	2, // 1: blackhole.BlackHole.EmitRandom:input_type -> blackhole.StreamSize
	2, // 2: blackhole.BlackHole.EmitZeros:input_type -> blackhole.StreamSize
	1, // 3: blackhole.BlackHole.ConsumeAll:output_type -> blackhole.ByteCount
	0, // 4: blackhole.BlackHole.EmitRandom:output_type -> blackhole.Bytes
	0, // 5: blackhole.BlackHole.EmitZeros:output_type -> blackhole.Bytes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blackhole_proto_init() }
func file_blackhole_proto_init() {
	if File_blackhole_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blackhole_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blackhole_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByteCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blackhole_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blackhole_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blackhole_proto_goTypes,
		DependencyIndexes: file_blackhole_proto_depIdxs,
		MessageInfos:      file_blackhole_proto_msgTypes,
	}.Build()
	File_blackhole_proto = out.File
	file_blackhole_proto_rawDesc = nil
	file_blackhole_proto_goTypes = nil
	file_blackhole_proto_depIdxs = nil
}
